# -*- coding: utf-8 -*-
"""RandomForestClassifier.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1z2hQIDDA-yyWhRGDGnCN4uMubeWhXlwg
"""

import pandas as pd

from sklearn.model_selection import train_test_split

from sklearn.ensemble import RandomForestClassifier

from sklearn.metrics import accuracy_score

df = pd.read_csv("/content/employee_promotion_prediction.csv")

df.head()

df.isnull().sum()

df = df.fillna(df.median(numeric_only=True))

df = df.dropna(subset=['promoted'])

print(df.select_dtypes(include='object').columns)

from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

for col in df.select_dtypes(include='object').columns:
    df[col] = le.fit_transform(df[col])

X = df.drop(
    ['employee_id','promoted'],
    axis=1
)

y = df['promoted']

y

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

model = RandomForestClassifier(
    n_estimators=100,
    random_state=42
)

model

model.fit(
    X_train,
    y_train
)

predictions = model.predict(X_test)

predictions

accuracy = accuracy_score(
    y_test,
    predictions
)

print("Accuracy:", accuracy)

from sklearn.metrics import confusion_matrix

cm = confusion_matrix(
    y_test,
    predictions
)

print(cm)

import seaborn as sns
import matplotlib.pyplot as plt

sns.heatmap(
    cm,
    annot=True,
    fmt='d'
)

plt.title("Confusion Matrix")

plt.xlabel("Predicted")

plt.ylabel("Actual")

plt.show()

new_employee = [X.iloc[0]]

prediction = model.predict(new_employee)

print(prediction)

sns.boxplot(
    x='promoted',
    y='salary',
    data=df
)

plt.show()

plt.figure(figsize=(12,8))

sns.heatmap(
    df.corr(numeric_only=True),
    cmap='coolwarm'
)

plt.show()



"""
Why Random Forest?

You have many employee factors:

Age
Education
Experience
Salary
Attendance
Engagement Score
Job Satisfaction
Performance Rating
Training Hours
Bonus
Stock Options

Promotion is not decided by one factor.

A single Decision Tree may:

Memorize data
Overfit
Give unstable predictions

Random Forest solves this by:

Building many Decision Trees
Combining their predictions
Using majority voting

Example:

Tree 1 → Promote

Tree 2 → Promote

Tree 3 → Don't Promote

Tree 4 → Promote

Tree 5 → Promote

Final Prediction:

Promote

because most trees voted for promotion."""